#ifndef INDEX_H
#define INDEX_H

static const char index_html[] =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"  <meta charset=\"UTF-8\">\n"
"  <title>ESP32S3 Camera & Temperature</title>\n"
"  <style>\n"
"    body {\n"
"      margin: 0;\n"
"      padding: 0;\n"
"      font-family: Arial, sans-serif;\n"
"      background: #000;\n"
"      color: #fff;\n"
"      text-align: center;\n"
"    }\n"
"    h1 {\n"
"      margin: 20px 0;\n"
"    }\n"
"    #videoStream {\n"
"      width: 1600px;\n"
"      height: 1200px;\n"
"      border: 2px solid #fff;\n"
"    }\n"
"    #tempBox {\n"
"      margin-top: 10px;\n"
"      font-size: 20px;\n"
"      background: rgba(0, 0, 0, 0.5);\n"
"      padding: 10px;\n"
"      border-radius: 5px;\n"
"      display: inline-block;\n"
"    }\n"
"    #downloadBtn {\n"
"      margin-top: 10px;\n"
"      padding: 10px 20px;\n"
"      font-size: 16px;\n"
"      border: none;\n"
"      border-radius: 5px;\n"
"      background: #4CAF50;\n"
"      color: white;\n"
"      cursor: pointer;\n"
"    }\n"
"    #downloadBtn:hover {\n"
"      background: #45a049;\n"
"    }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <h1>ESP32S3 Camera & Temperature</h1>\n"
"  <img id=\"videoStream\" alt=\"Camera Stream\"\n"
"       onerror=\"setTimeout(()=>{this.src='http://'+location.hostname+':81/stream?'+Date.now()},1000);\" />\n"
"  <div id=\"tempBox\">Temp: --°C</div>\n"
"  <br>\n"
"  <button id=\"downloadBtn\" onclick=\"downloadPicture()\">Download Picture</button>\n"
"\n"
"  <script>\n"
"    // Set the video stream source from port 81\n"
"    document.getElementById('videoStream').src = 'http://' + location.hostname + ':81/stream';\n"
"\n"
"    // Poll the temperature from the /temp endpoint every 5 seconds\n"
"    setInterval(() => {\n"
"      fetch('/temp')\n"
"        .then(response => response.json())\n"
"        .then(data => {\n"
"          document.getElementById('tempBox').textContent = 'Temp: ' + data.t.toFixed(2) + '°C';\n"
"        })\n"
"        .catch(err => console.error('Temperature fetch error:', err));\n"
"    }, 5000);\n"
"\n"
"    // Function to download a snapshot picture\n"
"    function downloadPicture() {\n"
"      // Create a temporary anchor element\n"
"      const a = document.createElement('a');\n"
"      // Set the href to the /capture endpoint with a timestamp to prevent caching\n"
"      a.href = 'http://' + location.hostname + '/capture?' + Date.now();\n"
"      a.download = 'snapshot.jpg';\n"
"      // Append the element, trigger click and remove the element\n"
"      document.body.appendChild(a);\n"
"      a.click();\n"
"      document.body.removeChild(a);\n"
"    }\n"
"  </script>\n"
"</body>\n"
"</html>\n";

#endif // INDEX_H